export * from "./types";
import type { ToolCategory, ToolDefinition } from "./types";

export const TOOLS: ToolDefinition[] = [
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPG, PNG, WebP images online for free.",
    category: "image",
    icon: "🗜️",
    keywords: ["compress", "image", "jpg", "png", "webp"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/ImageCompressorTool",
    isPopular: true,
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize images online to any dimension.",
    category: "image",
    icon: "↔️",
    keywords: ["resize", "image", "dimensions", "width", "height"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/ImageResizerTool",
    isPopular: true,
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG",
    description: "Convert PNG files to JPG format online.",
    category: "image",
    icon: "🖼️",
    keywords: ["png", "jpg", "convert", "image"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/PngToJpgTool",
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    description: "Convert JPG files to PNG format online.",
    category: "image",
    icon: "🖼️",
    keywords: ["jpg", "png", "convert", "image"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/JpgToPngTool",
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Convert images to Base64 encoded strings.",
    category: "image",
    icon: "🔤",
    keywords: ["image", "base64", "encode", "embed"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/ImageToBase64Tool",
    isNew: true,
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description:
      "Generate standard favicon sizes and a manifest snippet from an uploaded image.",
    category: "image",
    icon: "🧭",
    keywords: ["favicon", "icon", "web app", "manifest"],
    pattern: "generator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/FaviconGeneratorTool",
  },
  {
    slug: "exif-viewer-remover",
    name: "EXIF Viewer / Remover",
    description: "Inspect and strip metadata from photos before sharing.",
    category: "image",
    icon: "🕵️",
    keywords: ["exif", "metadata", "privacy", "photo"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/ExifViewerRemoverTool",
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop images visually in the browser.",
    category: "image",
    icon: "✂️",
    keywords: ["crop", "image", "resize", "canvas"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/ImageCropperTool",
  },
  {
    slug: "webp-converter",
    name: "WebP Converter",
    description: "Convert images between WebP, PNG and JPG.",
    category: "image",
    icon: "🟦",
    keywords: ["webp", "png", "jpg", "convert"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/WebpConverterTool",
    isNew: true,
  },
  {
    slug: "color-palette-extractor",
    name: "Color Palette Extractor",
    description: "Extract the dominant palette from an image.",
    category: "image",
    icon: "🎨",
    keywords: ["palette", "color", "extract", "image"],
    pattern: "analysis",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/ColorPaletteExtractorTool",
  },
  {
    slug: "image-watermark",
    name: "Image Watermark Tool",
    description: "Add text or image watermarks to your pictures.",
    category: "image",
    icon: "🔖",
    keywords: ["watermark", "image", "protect", "overlay"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/image/ImageWatermarkTool",
  },
  {
    slug: "text-diff-checker",
    name: "Text Diff Checker",
    description: "Compare two text blocks and highlight differences.",
    category: "text",
    icon: "⚔️",
    keywords: ["diff", "compare", "text", "changes"],
    pattern: "analysis",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/text/TextDiffCheckerTool",
  },
  {
    slug: "markdown-html-converter",
    name: "Markdown ↔ HTML Converter",
    description: "Convert Markdown to HTML and HTML back to Markdown.",
    category: "text",
    icon: "🌐",
    keywords: ["markdown", "html", "convert", "editor"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/text/MarkdownHtmlConverterTool",
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    description: "Read text aloud using your browser's speech synthesis.",
    category: "text",
    icon: "🔊",
    keywords: ["speech", "tts", "audio", "accessibility"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/text/TextToSpeechTool",
  },
  {
    slug: "find-replace",
    name: "Find & Replace",
    description: "Search and replace text across a block with regex support.",
    category: "text",
    icon: "🔎",
    keywords: ["find", "replace", "regex", "text"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/text/FindReplaceTool",
  },
  {
    slug: "social-media-counter",
    name: "Social Media Character Counter",
    description: "Track character limits for Twitter, Instagram, and LinkedIn.",
    category: "text",
    icon: "📏",
    keywords: ["social", "character", "count", "twitter"],
    pattern: "analysis",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/text/SocialMediaCounterTool",
  },
  {
    slug: "cron-expression-parser",
    name: "Cron Expression Parser",
    description:
      "Translate cron strings into readable schedules and next run times.",
    category: "developer",
    icon: "⏱️",
    keywords: ["cron", "schedule", "parser", "cron expression"],
    pattern: "analysis",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/CronExpressionParserTool",
  },
  {
    slug: "gitignore-generator",
    name: ".gitignore Generator",
    description: "Generate a tailored .gitignore file for your project stack.",
    category: "developer",
    icon: "📁",
    keywords: ["gitignore", "git", "ignore", "stack"],
    pattern: "generator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/GitignoreGeneratorTool",
  },
  {
    slug: "csv-json-converter",
    name: "CSV ↔ JSON Converter",
    description: "Convert CSV data to JSON and back for APIs and spreadsheets.",
    category: "developer",
    icon: "🧾",
    keywords: ["csv", "json", "convert", "spreadsheet"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/CsvJsonConverterTool",
  },
  {
    slug: "user-agent-parser",
    name: "User-Agent Parser",
    description: "Decode browser, OS, and device details from a UA string.",
    category: "developer",
    icon: "🧠",
    keywords: ["user agent", "browser", "device", "ua"],
    pattern: "analysis",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/UserAgentParserTool",
  },
  {
    slug: "http-status-reference",
    name: "HTTP Status Code Reference",
    description: "Search HTTP status codes and read real-world guidance.",
    category: "developer",
    icon: "📡",
    keywords: ["http", "status", "code", "404"],
    pattern: "reference",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/HttpStatusReferenceTool",
  },
  {
    slug: "semver-comparator",
    name: "Semver Comparator",
    description:
      "Compare semantic version strings and determine the newer release.",
    category: "developer",
    icon: "🔢",
    keywords: ["semver", "version", "compare", "npm"],
    pattern: "analysis",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/SemverComparatorTool",
  },
  {
    slug: "serp-snippet-preview",
    name: "SERP Snippet Preview",
    description:
      "Preview how title and description appear in Google search results.",
    category: "seo",
    icon: "🔎",
    keywords: ["serp", "preview", "seo", "google"],
    pattern: "analysis",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/seo/SerpSnippetPreviewTool",
  },
  {
    slug: "title-meta-description-checker",
    name: "Title/Meta Description Pixel-Width Checker",
    description:
      "Measure rendered pixel width to avoid search snippet truncation.",
    category: "seo",
    icon: "📐",
    keywords: ["title", "meta", "seo", "pixel width"],
    pattern: "analysis",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/seo/MetaPixelWidthCheckerTool",
  },
  {
    slug: "hreflang-generator",
    name: "Hreflang Tag Generator",
    description:
      "Build hreflang tags for international site language variants.",
    category: "seo",
    icon: "🌍",
    keywords: ["hreflang", "seo", "international", "language"],
    pattern: "markup",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/seo/HreflangGeneratorTool",
  },
  {
    slug: "keyword-density-checker",
    name: "Keyword Density Checker",
    description: "Analyze keyword frequency and density in your content.",
    category: "seo",
    icon: "🔠",
    keywords: ["keyword", "density", "seo", "content"],
    pattern: "analysis",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/seo/KeywordDensityCheckerTool",
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert length, weight, temperature and data size units.",
    category: "utility",
    icon: "📏",
    keywords: ["unit", "converter", "length", "weight"],
    pattern: "calculator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/utility/UnitConverterTool",
  },
  {
    slug: "age-date-difference",
    name: "Age / Date Difference Calculator",
    description: "Calculate age and date intervals between two dates.",
    category: "utility",
    icon: "🗓️",
    keywords: ["age", "date", "difference", "calculator"],
    pattern: "calculator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/utility/AgeDateDifferenceTool",
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate BMI from height and weight.",
    category: "utility",
    icon: "⚖️",
    keywords: ["bmi", "health", "weight", "calculator"],
    pattern: "calculator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/utility/BmiCalculatorTool",
  },
  {
    slug: "world-clock",
    name: "World Clock / Timezone Converter",
    description: "Convert times across time zones and compare clocks.",
    category: "utility",
    icon: "🌐",
    keywords: ["world clock", "timezone", "convert", "time"],
    pattern: "calculator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/utility/WorldClockTool",
  },
  {
    slug: "random-generators",
    name: "Random Generators Bundle",
    description: "Generate dice rolls, random numbers, names, and more.",
    category: "utility",
    icon: "🎲",
    keywords: ["random", "dice", "coin", "generator"],
    pattern: "generator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/utility/RandomGeneratorsTool",
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text between common casing styles.",
    category: "text",
    icon: "🔡",
    keywords: ["case", "uppercase", "lowercase", "convert"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/text/CaseConverterTool",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for mockups and layouts.",
    category: "text",
    icon: "📄",
    keywords: ["lorem", "ipsum", "placeholder", "dummy"],
    pattern: "generator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/text/LoremIpsumTool",
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Convert text into URL-friendly slugs.",
    category: "text",
    icon: "🔗",
    keywords: ["slug", "url", "friendly"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/text/SlugGeneratorTool",
    isNew: true,
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate and minify JSON payloads.",
    category: "developer",
    icon: "{ }",
    keywords: ["json", "format", "validate"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/JsonFormatterTool",
    isPopular: true,
  },
  {
    slug: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode Base64 strings.",
    category: "developer",
    icon: "🔐",
    keywords: ["base64", "encode", "decode"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/Base64EncoderTool",
  },
  {
    slug: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URLs for web use.",
    category: "developer",
    icon: "🌐",
    keywords: ["url", "encode", "decode"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/UrlEncoderTool",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs instantly.",
    category: "developer",
    icon: "🆔",
    keywords: ["uuid", "guid", "random"],
    pattern: "generator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/UuidGeneratorTool",
    isPopular: true,
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5 and SHA hashes.",
    category: "developer",
    icon: "#️⃣",
    keywords: ["hash", "md5", "sha"],
    pattern: "generator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/developer/HashGeneratorTool",
    isNew: true,
  },
  {
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate SEO meta tags and social cards.",
    category: "seo",
    icon: "🏷️",
    keywords: ["meta", "tag", "seo", "twitter"],
    pattern: "markup",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/seo/MetaTagGeneratorTool",
    isPopular: true,
  },
  {
    slug: "robots-generator",
    name: "Robots.txt Generator",
    description: "Generate a robots.txt file for your site.",
    category: "seo",
    icon: "🤖",
    keywords: ["robots", "txt", "seo", "crawl"],
    pattern: "markup",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/seo/RobotsGeneratorTool",
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate secure passwords with custom options.",
    category: "utility",
    icon: "🔑",
    keywords: ["password", "secure", "random"],
    pattern: "generator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/utility/PasswordGeneratorTool",
    isPopular: true,
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs and text.",
    category: "utility",
    icon: "⬛",
    keywords: ["qr", "code", "generate"],
    pattern: "generator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/utility/QrGeneratorTool",
    isPopular: true,
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    description: "Convert colors between HEX, RGB and HSL.",
    category: "utility",
    icon: "🎨",
    keywords: ["color", "picker", "hex", "rgb", "hsl"],
    pattern: "generator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/utility/ColorPickerTool",
    isNew: true,
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, changes and ratios.",
    category: "utility",
    icon: "%",
    keywords: ["percentage", "percent", "calculator"],
    pattern: "calculator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/utility/PercentageCalculatorTool",
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    description:
      "Calculate monthly loan payments, total payable amount, and interest.",
    category: "finance",
    icon: "💳",
    keywords: ["emi", "loan", "mortgage", "interest"],
    pattern: "calculator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/finance/EmiCalculatorTool",
    isNew: true,
  },
  {
    slug: "gst-calculator",
    name: "GST Calculator",
    description: "Compute GST, total payable amount, and taxable amount.",
    category: "finance",
    icon: "🧾",
    keywords: ["gst", "tax", "invoice", "rate"],
    pattern: "calculator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/finance/GstCalculatorTool",
  },
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    description:
      "Calculate return on investment, profit or loss, and total value.",
    category: "finance",
    icon: "📈",
    keywords: ["roi", "return", "investment", "profit"],
    pattern: "calculator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/finance/RoiCalculatorTool",
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    description:
      "Estimate compound interest growth for savings or investments.",
    category: "finance",
    icon: "📊",
    keywords: ["compound", "interest", "investment", "savings"],
    pattern: "calculator",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/finance/CompoundInterestCalculatorTool",
  },
  {
    slug: "markdown-editor",
    name: "Markdown Editor",
    description: "Write, preview, and export Markdown content online.",
    category: "text",
    icon: "📝",
    keywords: ["markdown", "editor", "preview", "text"],
    pattern: "transform",
    isFunctional: false,
    requiresAuth: false,
  },
  // ── PDF Tools ──────────────────────────────────────────────────────────────
  {
    slug: "pdf-merge",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one document.",
    category: "pdf",
    icon: "🔗",
    keywords: ["merge", "combine", "pdf", "join"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/pdf/PdfMergeTool",
    isNew: true,
    isPopular: true,
  },
  {
    slug: "pdf-split",
    name: "Split PDF",
    description: "Extract page ranges from a PDF into separate files.",
    category: "pdf",
    icon: "✂️",
    keywords: ["split", "pdf", "pages", "extract"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/pdf/PdfSplitTool",
    isNew: true,
  },
  {
    slug: "pdf-remove-pages",
    name: "Remove Pages from PDF",
    description: "Delete selected pages from a PDF file.",
    category: "pdf",
    icon: "🗑️",
    keywords: ["remove", "delete", "pages", "pdf"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/pdf/PdfRemovePagesTool",
    isNew: true,
  },
  {
    slug: "pdf-extract-pages",
    name: "Extract Pages from PDF",
    description: "Pull specific pages from a PDF into a new file.",
    category: "pdf",
    icon: "📤",
    keywords: ["extract", "pages", "pdf", "select"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/pdf/PdfExtractPagesTool",
    isNew: true,
  },
  {
    slug: "pdf-rotate",
    name: "Rotate PDF",
    description: "Rotate pages in a PDF by 90, 180, or 270 degrees.",
    category: "pdf",
    icon: "🔄",
    keywords: ["rotate", "pdf", "orientation", "pages"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/pdf/PdfRotateTool",
    isNew: true,
  },
  {
    slug: "pdf-add-page-numbers",
    name: "Add Page Numbers to PDF",
    description: "Stamp page numbers onto every page of a PDF.",
    category: "pdf",
    icon: "🔢",
    keywords: ["page numbers", "pdf", "stamp", "footer"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/pdf/PdfPageNumbersTool",
    isNew: true,
  },
  {
    slug: "pdf-watermark",
    name: "PDF Watermark",
    description: "Add a text or image watermark to every page of a PDF.",
    category: "pdf",
    icon: "💧",
    keywords: ["watermark", "pdf", "text", "overlay"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/pdf/PdfWatermarkTool",
    isNew: true,
  },
  {
    slug: "pdf-crop",
    name: "Crop PDF",
    description: "Crop the visible area of pages in a PDF file.",
    category: "pdf",
    icon: "✂️",
    keywords: ["crop", "pdf", "trim", "margins"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/pdf/PdfCropTool",
    isNew: true,
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Combine one or more images into a single PDF document.",
    category: "pdf",
    icon: "🖼️",
    keywords: ["jpg", "image", "pdf", "convert"],
    pattern: "file",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/pdf/JpgToPdfTool",
    isNew: true,
    isPopular: true,
  },
  {
    slug: "pdf-organize",
    name: "Organize PDF Pages",
    description: "Drag and drop to reorder pages in a PDF file.",
    category: "pdf",
    icon: "📋",
    keywords: ["organize", "reorder", "pdf", "pages", "drag"],
    pattern: "transform",
    isFunctional: true,
    requiresAuth: false,
    componentPath: "@/components/tools/pdf/PdfOrganizeTool",
    isNew: true,
  },
];

export const CATEGORIES: Record<
  ToolCategory,
  { label: string; description: string; icon: string; color: string }
> = {
  pdf: {
    label: "PDF Tools",
    description:
      "Free online PDF tools — merge PDFs, split, remove pages, rotate, add watermarks, add page numbers, crop, convert JPG to PDF, and reorder pages. All processing happens in your browser.",
    icon: "📄",
    color: "bg-red-50 text-red-700 border-red-200",
  },
  image: {
    label: "Image Tools",
    description:
      "Free online image tools — compress JPG/PNG/WebP, resize images, convert formats, crop, add watermarks, extract color palettes, and more. All processing happens in your browser.",
    icon: "🖼️",
    color: "bg-blue-50 text-blue-700 border-blue-200",
  },
  text: {
    label: "Text Tools",
    description:
      "Free online text tools — word counter, case converter, Lorem Ipsum generator, diff checker, Markdown-to-HTML converter, find & replace, social media character counter, and more.",
    icon: "📝",
    color: "bg-green-50 text-green-700 border-green-200",
  },
  developer: {
    label: "Developer Tools",
    description:
      "Free online developer utilities — JSON formatter, Base64 encoder/decoder, URL encoder, UUID generator, Hash generator, cron parser, .gitignore generator, CSV-to-JSON converter, and more.",
    icon: "⚡",
    color: "bg-purple-50 text-purple-700 border-purple-200",
  },
  seo: {
    label: "SEO Tools",
    description:
      "Free online SEO tools — meta tag generator, robots.txt generator, SERP snippet preview, pixel-width checker, hreflang tag generator, keyword density checker, and more.",
    icon: "🔍",
    color: "bg-orange-50 text-orange-700 border-orange-200",
  },
  utility: {
    label: "Utility Tools",
    description:
      "Free online utility tools — password generator, QR code generator, color picker, unit converter, BMI calculator, age calculator, world clock, percentage calculator, and more.",
    icon: "🛠️",
    color: "bg-teal-50 text-teal-700 border-teal-200",
  },
  finance: {
    label: "Finance Tools",
    description:
      "Free online finance calculators — EMI calculator, GST calculator, ROI calculator, compound interest calculator. Instant results, no data sent to any server.",
    icon: "💰",
    color: "bg-amber-50 text-amber-700 border-amber-200",
  },
};

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.category === category);
}

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS.find((tool) => tool.slug === slug);
}

export function searchTools(query: string): ToolDefinition[] {
  const term = query.toLowerCase();
  return TOOLS.filter((tool) => {
    return (
      tool.name.toLowerCase().includes(term) ||
      tool.description.toLowerCase().includes(term) ||
      tool.keywords.some((keyword) => keyword.includes(term))
    );
  });
}

export function getRelatedTools(
  tool: ToolDefinition,
  limit = 4,
): ToolDefinition[] {
  return TOOLS.filter(
    (candidate) =>
      candidate.slug !== tool.slug && candidate.category === tool.category,
  ).slice(0, limit);
}
