import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — ToolNest",
  description: "ToolNest terms of service. Simple, plain English terms for using the free online tools.",
};

const LAST_UPDATED = "June 28, 2025";
const CONTACT_EMAIL = "hello@toolnest.app";

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-14 sm:px-6">
      <div className="mb-10">
        <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white">Terms of Service</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: {LAST_UPDATED}</p>
        <div className="mt-4 rounded-xl bg-blue-50 border border-blue-200 px-5 py-4 text-sm text-blue-800 dark:bg-blue-950/20 dark:border-blue-800/40 dark:text-blue-300">
          <strong>Short version:</strong> Use the tools for lawful purposes. Don&apos;t abuse
          the service. Everything is provided as-is. That&apos;s basically it.
        </div>
      </div>

      <div className="space-y-8 text-slate-600 dark:text-slate-400">

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">1. Acceptance of terms</h2>
          <p>
            By using ToolNest (&quot;the site&quot;, &quot;the service&quot;), you agree to these terms.
            If you do not agree, please do not use the service. These terms apply to all
            visitors and users.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">2. Use of the service</h2>
          <p className="mb-3">You may use ToolNest for any lawful personal or commercial purpose. You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the service to process illegal, harmful, or malicious content</li>
            <li>Attempt to reverse engineer, scrape, or overload the service</li>
            <li>Use automated bots to mass-request tool functionality</li>
            <li>Resell or redistribute the tools as your own product without permission</li>
            <li>Attempt to bypass any rate limits or access controls</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">3. No warranties</h2>
          <p>
            ToolNest is provided &quot;as is&quot; without any warranty of any kind, express or implied.
            We do not guarantee that:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>The service will be uninterrupted or error-free</li>
            <li>Results from the tools are accurate or suitable for your specific use case</li>
            <li>The site will always be available</li>
          </ul>
          <p className="mt-3">
            Always verify critical output (hashes, encodings, generated content) before
            using it in production systems.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">4. Limitation of liability</h2>
          <p>
            To the maximum extent permitted by law, ToolNest and its operator (Uddhav Shrimali)
            shall not be liable for any indirect, incidental, or consequential damages
            arising from your use of the service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">5. Intellectual property</h2>
          <p>
            The ToolNest name, logo, design, and original content are owned by Uddhav Shrimali.
            The underlying tools and code are proprietary. You may not copy, redistribute,
            or create derivative products without explicit written permission.
          </p>
          <p className="mt-3">
            Output generated by the tools (compressed images, formatted JSON, generated
            passwords, etc.) belongs entirely to you.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">6. Third-party links</h2>
          <p>
            ToolNest may contain links to third-party websites (affiliate links, social media,
            documentation). We are not responsible for the content or privacy practices of
            those sites. Links do not imply endorsement.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">7. Advertising</h2>
          <p>
            ToolNest displays advertisements via Google AdSense to keep the service free.
            Ad content is controlled by Google and not by ToolNest. If you find an ad
            inappropriate, use Google&apos;s &quot;Why this ad?&quot; feature to report it.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">8. Donations</h2>
          <p>
            Voluntary donations via Buy Me a Coffee are gratefully accepted but provide
            no special access, features, or guarantees beyond our sincere thanks. Donations
            are non-refundable.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">9. Modifications</h2>
          <p>
            We reserve the right to modify or discontinue the service at any time. We may
            update these terms — continued use after changes constitutes acceptance. We&apos;ll
            update the &quot;Last updated&quot; date when changes occur.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">10. Governing law</h2>
          <p>
            These terms are governed by the laws of India. Any disputes shall be
            resolved in the courts of India.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">11. Contact</h2>
          <p>
            Questions about these terms? Email{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-indigo-600 hover:underline">
              {CONTACT_EMAIL}
            </a>.
          </p>
        </section>

      </div>

      <div className="mt-10 pt-6 border-t border-slate-200 dark:border-slate-700 flex flex-wrap gap-4 text-sm">
        <Link href="/privacy" className="text-indigo-600 hover:underline">Privacy Policy</Link>
        <Link href="/about" className="text-indigo-600 hover:underline">About ToolNest</Link>
        <Link href="/" className="text-indigo-600 hover:underline">← Back to tools</Link>
      </div>
    </div>
  );
}
